# Generated by Django 3.0 on 2021-03-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='codigo',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
